AI_PATTERNS = [
    r"generated by chatgpt",
    r"generated by ai",
    r"openai",
    r"copilot",
    r"anthropic",
    r"claude ai",
    r"todo: improve later",
    r"example implementation",
    r"placeholder content",
    r"sample data",
    r"auto-generated",
    r"do not modify this file",
]


COMMON_AI_HTML_PATTERNS = [
    "container mx-auto",
    "flex justify-center items-center",
    "bg-gray-100",
    'class="app"',
]

AI_SIGNATURES = [
    r"generated by chatgpt",
    r"as an ai language model",
    r"example implementation",
    r"todo: improve later",
    r"this function demonstrates",
    r"this code was generated by ai",
    r"here is an example implementation",
    r"you can modify this code as needed",
    r"copilot suggestion",
    r"github copilot",
    r"step\s*\d+\s*:",
    r"example usage:",
    r"let's break this down",
    r"in this example we",
]

DOCSTRING_PATTERNS = [
    r"Args:",
    r"Returns:",
    r"Example:",
    r"Usage:",
    r"This function (.*?) performs",
]

README_PATTERNS = [
    r"this project demonstrates",
    r"this repository provides",
    r"feel free to modify",
    r"for educational purposes",
]
LLM_FINGERPRINTS = [
    r"generated by",
    r"auto[- ]generated",
    r"do not modify",
    r"example implementation",
    r"placeholder content",
    r"eslint-disable",
    r"@generated",
    r"ai generated",
]
